version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/fastapi/Dockerfile
    volumes:
      - ./app/fastapi:/app/fastapi
      - ./data:/app/fastapi/data
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: app/main/Dockerfile
    volumes:
      - ./app/main:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    command: ["streamlit", "run", "/app/script_API.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
