name: Deploy Docker image to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.analyse-sentiment-app }}/web .
          docker push registry.heroku.com/${{ secrets.analyse-sentiment-app }}/web

      - name: Release app on Heroku
        run: heroku container:release web --app ${{ secrets.analyse-sentiment-app }}

      - name: Verify deployment
        run: curl https://$${{ secrets.analyse-sentiment-app }}.herokuapp.com